### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by rhansen**
* Move userinfo fetch inside try block
  * Delete unnecessary `req.`
  * Delete invalid `req.logout()` in `/logout` endpoint
  * Escape the period in socket.io
  * Delete unnecessary repetition of function names
  * Typo fix ("setting setting" -> "setting")
  * Delete unnecessary authorManager.createAuthorIfNotExistsFor call
  * Let Express handle exceptions in authCallback
  * Defer deletion of OAuth state
  * Throw an error if nonce or state is missing from session
  * Put OAuth nonce and state in object to simplify
  * Add 'OAuth' to the package tags
  * Make sure handleMessage always returns a promise
  * Check in `package-lock.json`

### CODE REVIEW

**Comment by rhansen** [comment]
Friendly ping @stefanor.

**Comment by rhansen** [comment]
@stefanor Due to lack of response I forked this project as [ep_openid_connect](https://github.com/ether/ep_openid_connect/). That fork contains all of these fixes and more.

**Comment by stefanor** [comment]
Thanks, been meaning to get to these. But a new maintainer is even better :)

**Comment by stefanor** [comment]
I'll happily hand over the npm package.

**Pull request closed without merging**
